### ISSUE TITLE
Test exception in thread

### ISSUE THREAD

**Issue by gnovis** [Cognexa/cxflow#140]
When you run `python setup.py test`, the below exception is raised. The exception is not included  in test report (all tests passed).
```
test_enqueueing_thread_exception (cxflow.tests.datasets.stream_wrapper_test.StreamWrapperTest) ... Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/jnovacek/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jnovacek/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jnovacek/work/projects/cxflow/cxflow/datasets/stream_wrapper.py", line 105, in _enqueue_batches
    for batch in self._get_stream():
  File "/home/jnovacek/work/projects/cxflow/cxflow/tests/datasets/stream_wrapper_test.py", line 14, in train_stream
    raise RuntimeError('Explosion.')
RuntimeError: Explosion.
```

**Comment by blazekadam** [comment]
The exception is actually expected. It is raised in a different thread; hence, we see the output.
