### ISSUE TITLE
LogProfile hook fails on an empty train stream

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxflow#187]
In case of empty batch, the log profiling hook terminates with hardly readable error:

```
ERROR   @util           : 'eval_batch_train'
Traceback (most recent call last):
  File "/home/petrbel/.local/lib/python3.6/site-packages/cxflow/cli/common.py", line 288, in run
    main_loop.run_training(trace)
  File "/home/petrbel/.local/lib/python3.6/site-packages/cxflow/main_loop.py", line 267, in run_training
    self._try_run(training)
  File "/home/petrbel/.local/lib/python3.6/site-packages/cxflow/main_loop.py", line 212, in _try_run
    run_func()
  File "/home/petrbel/.local/lib/python3.6/site-packages/cxflow/main_loop.py", line 261, in training
    extra_streams=self._extra_streams)
  File "/home/petrbel/.local/lib/python3.6/site-packages/cxflow/hooks/log_profile.py", line 42, in after_epoch_profile
    train_total = sum(profile['eval_batch_train'])
KeyError: 'eval_batch_train'
```

It should check whether the batch is empty.

**Comment by blazekadam** [comment]
It caused by an empty train stream, not by an empty batch. Updating the title.
